name = "mcp-server"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[build]
command = "npm run build"

[durable_objects]
bindings = [
  { name = "CONNECTIONS", class_name = "MCPConnectionsDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["MCPConnectionsDO"] 