name = "mcp-server"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[build]
command = "npm run build"

[durable_objects]
bindings = [
  { name = "CONNECTIONS", class_name = "MCPConnectionsDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["MCPConnectionsDO"] 

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "stock-db"
database_id = "43ecab0b-d937-4395-b6cb-383ff59d9aff"
